<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE graph [
<!ELEMENT graph (data-type, display+, node+, edge+)>
<!ELEMENT data-type (#PCDATA)>
<!ELEMENT display (node-color, edge-color, max-edge-width)>
<!ELEMENT node-color (#PCDATA)>
<!ELEMENT edge-color (#PCDATA)>
<!ELEMENT max-edge-width (#PCDATA)>
<!ELEMENT node (id, super-node, label, weight, type)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT super-node (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT edge (from, to, type, weight)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
]>
<graph>
<data-type>file-system</data-type>
<display>
	<node-color>0,0,255</node-color>
	<edge-color>100,100,100</edge-color>
	<max-edge-width>40</max-edge-width>
</display>
<node>
	<id>0</id>
	<super-node>false</super-node>
	<label>.</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>1</id>
	<super-node>false</super-node>
	<label>bin</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>2</id>
	<super-node>false</super-node>
	<label>appletviewer.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>3</id>
	<super-node>false</super-node>
	<label>apt.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>4</id>
	<super-node>false</super-node>
	<label>beanreg.dll</label>
	<weight>30</weight>
	<type>4</type>
</node>
<node>
	<id>5</id>
	<super-node>false</super-node>
	<label>extcheck.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>6</id>
	<super-node>false</super-node>
	<label>HtmlConverter.exe</label>
	<weight>55</weight>
	<type>4</type>
</node>
<node>
	<id>7</id>
	<super-node>false</super-node>
	<label>idlj.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>8</id>
	<super-node>false</super-node>
	<label>jar.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>9</id>
	<super-node>false</super-node>
	<label>jarsigner.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>10</id>
	<super-node>false</super-node>
	<label>java-rmi.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>11</id>
	<super-node>false</super-node>
	<label>java.exe</label>
	<weight>145</weight>
	<type>4</type>
</node>
<node>
	<id>12</id>
	<super-node>false</super-node>
	<label>javac.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>13</id>
	<super-node>false</super-node>
	<label>javadoc.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>14</id>
	<super-node>false</super-node>
	<label>javah.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>15</id>
	<super-node>false</super-node>
	<label>javap.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>16</id>
	<super-node>false</super-node>
	<label>javaw.exe</label>
	<weight>145</weight>
	<type>4</type>
</node>
<node>
	<id>17</id>
	<super-node>false</super-node>
	<label>javaws.exe</label>
	<weight>157</weight>
	<type>4</type>
</node>
<node>
	<id>18</id>
	<super-node>false</super-node>
	<label>jconsole.exe</label>
	<weight>34</weight>
	<type>4</type>
</node>
<node>
	<id>19</id>
	<super-node>false</super-node>
	<label>jdb.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>20</id>
	<super-node>false</super-node>
	<label>jhat.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>21</id>
	<super-node>false</super-node>
	<label>jinfo.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>22</id>
	<super-node>false</super-node>
	<label>jli.dll</label>
	<weight>77</weight>
	<type>4</type>
</node>
<node>
	<id>23</id>
	<super-node>false</super-node>
	<label>jmap.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>24</id>
	<super-node>false</super-node>
	<label>jps.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>25</id>
	<super-node>false</super-node>
	<label>jrunscript.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>26</id>
	<super-node>false</super-node>
	<label>jstack.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>27</id>
	<super-node>false</super-node>
	<label>jstat.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>28</id>
	<super-node>false</super-node>
	<label>jstatd.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>29</id>
	<super-node>false</super-node>
	<label>jvisualvm.exe</label>
	<weight>47</weight>
	<type>4</type>
</node>
<node>
	<id>30</id>
	<super-node>false</super-node>
	<label>keytool.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>31</id>
	<super-node>false</super-node>
	<label>kinit.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>32</id>
	<super-node>false</super-node>
	<label>klist.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>33</id>
	<super-node>false</super-node>
	<label>ktab.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>34</id>
	<super-node>false</super-node>
	<label>msvcr71.dll</label>
	<weight>348</weight>
	<type>4</type>
</node>
<node>
	<id>35</id>
	<super-node>false</super-node>
	<label>native2ascii.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>36</id>
	<super-node>false</super-node>
	<label>orbd.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>37</id>
	<super-node>false</super-node>
	<label>pack200.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>38</id>
	<super-node>false</super-node>
	<label>packager.exe</label>
	<weight>79</weight>
	<type>4</type>
</node>
<node>
	<id>39</id>
	<super-node>false</super-node>
	<label>policytool.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>40</id>
	<super-node>false</super-node>
	<label>rmic.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>41</id>
	<super-node>false</super-node>
	<label>rmid.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>42</id>
	<super-node>false</super-node>
	<label>rmiregistry.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>43</id>
	<super-node>false</super-node>
	<label>schemagen.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>44</id>
	<super-node>false</super-node>
	<label>serialver.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>45</id>
	<super-node>false</super-node>
	<label>servertool.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>46</id>
	<super-node>false</super-node>
	<label>tnameserv.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>47</id>
	<super-node>false</super-node>
	<label>unpack200.exe</label>
	<weight>132</weight>
	<type>4</type>
</node>
<node>
	<id>48</id>
	<super-node>false</super-node>
	<label>wsgen.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>49</id>
	<super-node>false</super-node>
	<label>wsimport.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>50</id>
	<super-node>false</super-node>
	<label>xjc.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>51</id>
	<super-node>false</super-node>
	<label>COPYRIGHT</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>52</id>
	<super-node>false</super-node>
	<label>demo</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>53</id>
	<super-node>false</super-node>
	<label>applets</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>54</id>
	<super-node>false</super-node>
	<label>Animator</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>55</id>
	<super-node>false</super-node>
	<label>Animation.class</label>
	<weight>7</weight>
	<type>3</type>
</node>
<node>
	<id>56</id>
	<super-node>false</super-node>
	<label>AnimationFrame.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>57</id>
	<super-node>false</super-node>
	<label>Animator.class</label>
	<weight>10</weight>
	<type>3</type>
</node>
<node>
	<id>58</id>
	<super-node>false</super-node>
	<label>Animator.java</label>
	<weight>29</weight>
	<type>3</type>
</node>
<node>
	<id>59</id>
	<super-node>false</super-node>
	<label>audio</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>60</id>
	<super-node>false</super-node>
	<label>0.au</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>61</id>
	<super-node>false</super-node>
	<label>1.au</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>62</id>
	<super-node>false</super-node>
	<label>2.au</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>63</id>
	<super-node>false</super-node>
	<label>3.au</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>64</id>
	<super-node>false</super-node>
	<label>4.au</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>65</id>
	<super-node>false</super-node>
	<label>5.au</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>66</id>
	<super-node>false</super-node>
	<label>6.au</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>67</id>
	<super-node>false</super-node>
	<label>7.au</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>68</id>
	<super-node>false</super-node>
	<label>8.au</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>69</id>
	<super-node>false</super-node>
	<label>9.au</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>70</id>
	<super-node>false</super-node>
	<label>spacemusic.au</label>
	<weight>48</weight>
	<type>-1</type>
</node>
<node>
	<id>71</id>
	<super-node>false</super-node>
	<label>DescriptionFrame.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>72</id>
	<super-node>false</super-node>
	<label>example1.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>73</id>
	<super-node>false</super-node>
	<label>example2.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>74</id>
	<super-node>false</super-node>
	<label>example3.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>75</id>
	<super-node>false</super-node>
	<label>example4.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>76</id>
	<super-node>false</super-node>
	<label>images</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>77</id>
	<super-node>false</super-node>
	<label>Beans</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>78</id>
	<super-node>false</super-node>
	<label>T1.gif</label>
	<weight>10</weight>
	<type>-1</type>
</node>
<node>
	<id>79</id>
	<super-node>false</super-node>
	<label>T10.gif</label>
	<weight>13</weight>
	<type>-1</type>
</node>
<node>
	<id>80</id>
	<super-node>false</super-node>
	<label>T2.gif</label>
	<weight>11</weight>
	<type>-1</type>
</node>
<node>
	<id>81</id>
	<super-node>false</super-node>
	<label>T3.gif</label>
	<weight>11</weight>
	<type>-1</type>
</node>
<node>
	<id>82</id>
	<super-node>false</super-node>
	<label>T4.gif</label>
	<weight>12</weight>
	<type>-1</type>
</node>
<node>
	<id>83</id>
	<super-node>false</super-node>
	<label>T5.gif</label>
	<weight>10</weight>
	<type>-1</type>
</node>
<node>
	<id>84</id>
	<super-node>false</super-node>
	<label>T6.gif</label>
	<weight>7</weight>
	<type>-1</type>
</node>
<node>
	<id>85</id>
	<super-node>false</super-node>
	<label>T7.gif</label>
	<weight>8</weight>
	<type>-1</type>
</node>
<node>
	<id>86</id>
	<super-node>false</super-node>
	<label>T8.gif</label>
	<weight>12</weight>
	<type>-1</type>
</node>
<node>
	<id>87</id>
	<super-node>false</super-node>
	<label>T9.gif</label>
	<weight>10</weight>
	<type>-1</type>
</node>
<node>
	<id>88</id>
	<super-node>false</super-node>
	<label>loading-msg.gif</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>89</id>
	<super-node>false</super-node>
	<label>SimpleAnimation</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>90</id>
	<super-node>false</super-node>
	<label>T1.gif</label>
	<weight>4</weight>
	<type>-1</type>
</node>
<node>
	<id>91</id>
	<super-node>false</super-node>
	<label>T2.gif</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>92</id>
	<super-node>false</super-node>
	<label>index.html</label>
	<weight>6</weight>
	<type>3</type>
</node>
<node>
	<id>93</id>
	<super-node>false</super-node>
	<label>ParseException.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>94</id>
	<super-node>false</super-node>
	<label>ArcTest</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>95</id>
	<super-node>false</super-node>
	<label>ArcCanvas.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>96</id>
	<super-node>false</super-node>
	<label>ArcControls.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>97</id>
	<super-node>false</super-node>
	<label>ArcTest.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>98</id>
	<super-node>false</super-node>
	<label>ArcTest.java</label>
	<weight>7</weight>
	<type>3</type>
</node>
<node>
	<id>99</id>
	<super-node>false</super-node>
	<label>example1.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>100</id>
	<super-node>false</super-node>
	<label>IntegerTextField.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>101</id>
	<super-node>false</super-node>
	<label>BarChart</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>102</id>
	<super-node>false</super-node>
	<label>BarChart.class</label>
	<weight>6</weight>
	<type>3</type>
</node>
<node>
	<id>103</id>
	<super-node>false</super-node>
	<label>BarChart.java</label>
	<weight>11</weight>
	<type>3</type>
</node>
<node>
	<id>104</id>
	<super-node>false</super-node>
	<label>example1.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>105</id>
	<super-node>false</super-node>
	<label>Blink</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>106</id>
	<super-node>false</super-node>
	<label>Blink$1.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>107</id>
	<super-node>false</super-node>
	<label>Blink.class</label>
	<weight>2</weight>
	<type>3</type>
</node>
<node>
	<id>108</id>
	<super-node>false</super-node>
	<label>Blink.java</label>
	<weight>4</weight>
	<type>3</type>
</node>
<node>
	<id>109</id>
	<super-node>false</super-node>
	<label>example1.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>110</id>
	<super-node>false</super-node>
	<label>CardTest</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>111</id>
	<super-node>false</super-node>
	<label>CardPanel.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>112</id>
	<super-node>false</super-node>
	<label>CardTest.class</label>
	<weight>2</weight>
	<type>3</type>
</node>
<node>
	<id>113</id>
	<super-node>false</super-node>
	<label>CardTest.java</label>
	<weight>4</weight>
	<type>3</type>
</node>
<node>
	<id>114</id>
	<super-node>false</super-node>
	<label>example1.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>115</id>
	<super-node>false</super-node>
	<label>Clock</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>116</id>
	<super-node>false</super-node>
	<label>Clock.class</label>
	<weight>4</weight>
	<type>3</type>
</node>
<node>
	<id>117</id>
	<super-node>false</super-node>
	<label>Clock.java</label>
	<weight>8</weight>
	<type>3</type>
</node>
<node>
	<id>118</id>
	<super-node>false</super-node>
	<label>example1.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>119</id>
	<super-node>false</super-node>
	<label>DitherTest</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>120</id>
	<super-node>false</super-node>
	<label>CardinalTextField.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>121</id>
	<super-node>false</super-node>
	<label>DitherCanvas.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>122</id>
	<super-node>false</super-node>
	<label>DitherControls.class</label>
	<weight>2</weight>
	<type>3</type>
</node>
<node>
	<id>123</id>
	<super-node>false</super-node>
	<label>DitherTest.class</label>
	<weight>4</weight>
	<type>3</type>
</node>
<node>
	<id>124</id>
	<super-node>false</super-node>
	<label>DitherTest.java</label>
	<weight>14</weight>
	<type>3</type>
</node>
<node>
	<id>125</id>
	<super-node>false</super-node>
	<label>example1.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>126</id>
	<super-node>false</super-node>
	<label>DrawTest</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>127</id>
	<super-node>false</super-node>
	<label>DrawControls.class</label>
	<weight>2</weight>
	<type>3</type>
</node>
<node>
	<id>128</id>
	<super-node>false</super-node>
	<label>DrawPanel.class</label>
	<weight>2</weight>
	<type>3</type>
</node>
<node>
	<id>129</id>
	<super-node>false</super-node>
	<label>DrawTest.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>130</id>
	<super-node>false</super-node>
	<label>DrawTest.java</label>
	<weight>7</weight>
	<type>3</type>
</node>
<node>
	<id>131</id>
	<super-node>false</super-node>
	<label>example1.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>132</id>
	<super-node>false</super-node>
	<label>Fractal</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>133</id>
	<super-node>false</super-node>
	<label>CLSFractal.class</label>
	<weight>5</weight>
	<type>3</type>
</node>
<node>
	<id>134</id>
	<super-node>false</super-node>
	<label>CLSFractal.java</label>
	<weight>12</weight>
	<type>3</type>
</node>
<node>
	<id>135</id>
	<super-node>false</super-node>
	<label>CLSRule.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>136</id>
	<super-node>false</super-node>
	<label>CLSTurtle.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>137</id>
	<super-node>false</super-node>
	<label>ContextLSystem.class</label>
	<weight>2</weight>
	<type>3</type>
</node>
<node>
	<id>138</id>
	<super-node>false</super-node>
	<label>example1.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>139</id>
	<super-node>false</super-node>
	<label>GraphicsTest</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>140</id>
	<super-node>false</super-node>
	<label>AppletFrame.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>141</id>
	<super-node>false</super-node>
	<label>AppletFrame.java</label>
	<weight>3</weight>
	<type>3</type>
</node>
<node>
	<id>142</id>
	<super-node>false</super-node>
	<label>ArcCard.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>143</id>
	<super-node>false</super-node>
	<label>ArcDegreePanel.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>144</id>
	<super-node>false</super-node>
	<label>ArcPanel.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>145</id>
	<super-node>false</super-node>
	<label>ColorUtils.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>146</id>
	<super-node>false</super-node>
	<label>example1.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>147</id>
	<super-node>false</super-node>
	<label>GraphicsCards.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>148</id>
	<super-node>false</super-node>
	<label>GraphicsPanel.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>149</id>
	<super-node>false</super-node>
	<label>GraphicsTest.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>150</id>
	<super-node>false</super-node>
	<label>GraphicsTest.java</label>
	<weight>11</weight>
	<type>3</type>
</node>
<node>
	<id>151</id>
	<super-node>false</super-node>
	<label>OvalShape.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>152</id>
	<super-node>false</super-node>
	<label>PolygonShape.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>153</id>
	<super-node>false</super-node>
	<label>RectShape.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>154</id>
	<super-node>false</super-node>
	<label>RoundRectShape.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>155</id>
	<super-node>false</super-node>
	<label>Shape.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>156</id>
	<super-node>false</super-node>
	<label>ShapeTest.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>157</id>
	<super-node>false</super-node>
	<label>GraphLayout</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>158</id>
	<super-node>false</super-node>
	<label>audio</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>159</id>
	<super-node>false</super-node>
	<label>computer.au</label>
	<weight>21</weight>
	<type>-1</type>
</node>
<node>
	<id>160</id>
	<super-node>false</super-node>
	<label>drip.au</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>161</id>
	<super-node>false</super-node>
	<label>gong.au</label>
	<weight>42</weight>
	<type>-1</type>
</node>
<node>
	<id>162</id>
	<super-node>false</super-node>
	<label>Edge.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>163</id>
	<super-node>false</super-node>
	<label>example1.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>164</id>
	<super-node>false</super-node>
	<label>example2.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>165</id>
	<super-node>false</super-node>
	<label>example3.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>166</id>
	<super-node>false</super-node>
	<label>example4.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>167</id>
	<super-node>false</super-node>
	<label>Graph.class</label>
	<weight>4</weight>
	<type>3</type>
</node>
<node>
	<id>168</id>
	<super-node>false</super-node>
	<label>Graph.java</label>
	<weight>11</weight>
	<type>3</type>
</node>
<node>
	<id>169</id>
	<super-node>false</super-node>
	<label>GraphPanel.class</label>
	<weight>7</weight>
	<type>3</type>
</node>
<node>
	<id>170</id>
	<super-node>false</super-node>
	<label>Node.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>171</id>
	<super-node>false</super-node>
	<label>ImageMap</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>172</id>
	<super-node>false</super-node>
	<label>AniArea.class</label>
	<weight>2</weight>
	<type>3</type>
</node>
<node>
	<id>173</id>
	<super-node>false</super-node>
	<label>AniArea.java</label>
	<weight>3</weight>
	<type>3</type>
</node>
<node>
	<id>174</id>
	<super-node>false</super-node>
	<label>audio</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>175</id>
	<super-node>false</super-node>
	<label>chirp1.au</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>176</id>
	<super-node>false</super-node>
	<label>hi.au</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>177</id>
	<super-node>false</super-node>
	<label>ButtonFilter.class</label>
	<weight>3</weight>
	<type>3</type>
</node>
<node>
	<id>178</id>
	<super-node>false</super-node>
	<label>ButtonFilter.java</label>
	<weight>8</weight>
	<type>3</type>
</node>
<node>
	<id>179</id>
	<super-node>false</super-node>
	<label>ClickArea.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>180</id>
	<super-node>false</super-node>
	<label>ClickArea.java</label>
	<weight>3</weight>
	<type>3</type>
</node>
<node>
	<id>181</id>
	<super-node>false</super-node>
	<label>DelayedSoundArea.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>182</id>
	<super-node>false</super-node>
	<label>DelayedSoundArea.java</label>
	<weight>3</weight>
	<type>3</type>
</node>
<node>
	<id>183</id>
	<super-node>false</super-node>
	<label>example1.html</label>
	<weight>2</weight>
	<type>3</type>
</node>
<node>
	<id>184</id>
	<super-node>false</super-node>
	<label>HighlightArea.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>185</id>
	<super-node>false</super-node>
	<label>HighlightArea.java</label>
	<weight>3</weight>
	<type>3</type>
</node>
<node>
	<id>186</id>
	<super-node>false</super-node>
	<label>HighlightFilter.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>187</id>
	<super-node>false</super-node>
	<label>HighlightFilter.java</label>
	<weight>3</weight>
	<type>3</type>
</node>
<node>
	<id>188</id>
	<super-node>false</super-node>
	<label>HrefButtonArea.class</label>
	<weight>2</weight>
	<type>3</type>
</node>
<node>
	<id>189</id>
	<super-node>false</super-node>
	<label>HrefButtonArea.java</label>
	<weight>4</weight>
	<type>3</type>
</node>
<node>
	<id>190</id>
	<super-node>false</super-node>
	<label>ImageMap.class</label>
	<weight>10</weight>
	<type>3</type>
</node>
<node>
	<id>191</id>
	<super-node>false</super-node>
	<label>ImageMap.java</label>
	<weight>14</weight>
	<type>3</type>
</node>
<node>
	<id>192</id>
	<super-node>false</super-node>
	<label>ImageMapArea.class</label>
	<weight>3</weight>
	<type>3</type>
</node>
<node>
	<id>193</id>
	<super-node>false</super-node>
	<label>ImageMapArea.java</label>
	<weight>11</weight>
	<type>3</type>
</node>
<node>
	<id>194</id>
	<super-node>false</super-node>
	<label>imagemapcheat.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>195</id>
	<super-node>false</super-node>
	<label>images</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>196</id>
	<super-node>false</super-node>
	<label>jim.graham.gif</label>
	<weight>135</weight>
	<type>-1</type>
</node>
<node>
	<id>197</id>
	<super-node>false</super-node>
	<label>LinkArea.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>198</id>
	<super-node>false</super-node>
	<label>LinkArea.java</label>
	<weight>3</weight>
	<type>3</type>
</node>
<node>
	<id>199</id>
	<super-node>false</super-node>
	<label>NameArea.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>200</id>
	<super-node>false</super-node>
	<label>NameArea.java</label>
	<weight>2</weight>
	<type>3</type>
</node>
<node>
	<id>201</id>
	<super-node>false</super-node>
	<label>RoundButtonFilter.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>202</id>
	<super-node>false</super-node>
	<label>RoundButtonFilter.java</label>
	<weight>4</weight>
	<type>3</type>
</node>
<node>
	<id>203</id>
	<super-node>false</super-node>
	<label>RoundHrefButtonArea.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>204</id>
	<super-node>false</super-node>
	<label>RoundHrefButtonArea.java</label>
	<weight>2</weight>
	<type>3</type>
</node>
<node>
	<id>205</id>
	<super-node>false</super-node>
	<label>SoundArea.class</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>206</id>
	<super-node>false</super-node>
	<label>SoundArea.java</label>
	<weight>4</weight>
	<type>3</type>
</node>
<node>
	<id>207</id>
	<super-node>false</super-node>
	<label>sources.html</label>
	<weight>3</weight>
	<type>3</type>
</node>
<node>
	<id>208</id>
	<super-node>false</super-node>
	<label>TickerArea.class</label>
	<weight>2</weight>
	<type>3</type>
</node>
<node>
	<id>209</id>
	<super-node>false</super-node>
	<label>TickerArea.java</label>
	<weight>4</weight>
	<type>3</type>
</node>
<node>
	<id>210</id>
	<super-node>false</super-node>
	<label>JumpingBox</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>211</id>
	<super-node>false</super-node>
	<label>example1.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>212</id>
	<super-node>false</super-node>
	<label>JumpingBox.class</label>
	<weight>4</weight>
	<type>3</type>
</node>
<node>
	<id>213</id>
	<super-node>false</super-node>
	<label>JumpingBox.java</label>
	<weight>5</weight>
	<type>3</type>
</node>
<node>
	<id>214</id>
	<super-node>false</super-node>
	<label>sounds</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>215</id>
	<super-node>false</super-node>
	<label>adapt-or-die.au</label>
	<weight>2</weight>
	<type>-1</type>
</node>
<node>
	<id>216</id>
	<super-node>false</super-node>
	<label>cannot.be.completed.au</label>
	<weight>13</weight>
	<type>-1</type>
</node>
<node>
	<id>217</id>
	<super-node>false</super-node>
	<label>danger.au</label>
	<weight>12</weight>
	<type>-1</type>
</node>
<node>
	<id>218</id>
	<super-node>false</super-node>
	<label>ip.au</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>219</id>
	<super-node>false</super-node>
	<label>that.hurts.au</label>
	<weight>13</weight>
	<type>-1</type>
</node>
<node>
	<id>220</id>
	<super-node>false</super-node>
	<label>thin.bell.au</label>
	<weight>2</weight>
	<type>-1</type>
</node>
<node>
	<id>221</id>
	<super-node>false</super-node>
	<label>tiptoe.thru.the.tulips.au</label>
	<weight>6</weight>
	<type>-1</type>
</node>
<node>
	<id>222</id>
	<super-node>false</super-node>
	<label>MoleculeViewer</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>223</id>
	<super-node>false</super-node>
	<label>Atom.class</label>
	<weight>2</weight>
	<type>3</type>
</node>
<node>
	<id>224</id>
	<super-node>false</super-node>
	<label>example1.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>225</id>
	<super-node>false</super-node>
	<label>example2.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>226</id>
	<super-node>false</super-node>
	<label>example3.html</label>
	<weight>1</weight>
	<type>3</type>
</node>
<node>
	<id>227</id>
	<super-node>false</super-node>
	<label>Matrix3D.class</label>
	<weight>3</weight>
	<type>3</type>
</node>
<node>
	<id>228</id>
	<super-node>false</super-node>
	<label>Matrix3D.java</label>
	<weight>6</weight>
	<type>3</type>
</node>
<node>
	<id>229</id>
	<super-node>false</super-node>
	<label>models</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>230</id>
	<super-node>false</super-node>
	<label>benzene.xyz</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>231</id>
	<super-node>false</super-node>