<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE graph [
<!ELEMENT graph (data-type, display+, node+, edge+)>
<!ELEMENT data-type (#PCDATA)>
<!ELEMENT display (node-color, edge-color, max-edge-width)>
<!ELEMENT node-color (#PCDATA)>
<!ELEMENT edge-color (#PCDATA)>
<!ELEMENT max-edge-width (#PCDATA)>
<!ELEMENT node (id, super-node, label, weight, type)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT super-node (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT edge (from, to, type, weight)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
]>
<graph>
<data-type>file-system</data-type>
<display>
	<node-color>0,0,255</node-color>
	<edge-color>100,100,100</edge-color>
	<max-edge-width>40</max-edge-width>
</display>
<node>
	<id>0</id>
	<super-node>false</super-node>
	<label>.</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>1</id>
	<super-node>false</super-node>
	<label>bin</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>2</id>
	<super-node>false</super-node>
	<label>attach.dll</label>
	<weight>10</weight>
	<type>4</type>
</node>
<node>
	<id>3</id>
	<super-node>false</super-node>
	<label>awt.dll</label>
	<weight>1208</weight>
	<type>4</type>
</node>
<node>
	<id>4</id>
	<super-node>false</super-node>
	<label>axbridge.dll</label>
	<weight>118</weight>
	<type>4</type>
</node>
<node>
	<id>5</id>
	<super-node>false</super-node>
	<label>client</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>6</id>
	<super-node>false</super-node>
	<label>classes.jsa</label>
	<weight>13762</weight>
	<type>-1</type>
</node>
<node>
	<id>7</id>
	<super-node>false</super-node>
	<label>jvm.dll</label>
	<weight>2719</weight>
	<type>4</type>
</node>
<node>
	<id>8</id>
	<super-node>false</super-node>
	<label>Xusage.txt</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>9</id>
	<super-node>false</super-node>
	<label>cmm.dll</label>
	<weight>192</weight>
	<type>4</type>
</node>
<node>
	<id>10</id>
	<super-node>false</super-node>
	<label>dcpr.dll</label>
	<weight>143</weight>
	<type>4</type>
</node>
<node>
	<id>11</id>
	<super-node>false</super-node>
	<label>deploy.dll</label>
	<weight>77</weight>
	<type>4</type>
</node>
<node>
	<id>12</id>
	<super-node>false</super-node>
	<label>deployJava1.dll</label>
	<weight>472</weight>
	<type>4</type>
</node>
<node>
	<id>13</id>
	<super-node>false</super-node>
	<label>dt_shmem.dll</label>
	<weight>16</weight>
	<type>4</type>
</node>
<node>
	<id>14</id>
	<super-node>false</super-node>
	<label>dt_socket.dll</label>
	<weight>13</weight>
	<type>4</type>
</node>
<node>
	<id>15</id>
	<super-node>false</super-node>
	<label>eula.dll</label>
	<weight>94</weight>
	<type>4</type>
</node>
<node>
	<id>16</id>
	<super-node>false</super-node>
	<label>fontmanager.dll</label>
	<weight>323</weight>
	<type>4</type>
</node>
<node>
	<id>17</id>
	<super-node>false</super-node>
	<label>hpi.dll</label>
	<weight>15</weight>
	<type>4</type>
</node>
<node>
	<id>18</id>
	<super-node>false</super-node>
	<label>hprof.dll</label>
	<weight>139</weight>
	<type>4</type>
</node>
<node>
	<id>19</id>
	<super-node>false</super-node>
	<label>instrument.dll</label>
	<weight>98</weight>
	<type>4</type>
</node>
<node>
	<id>20</id>
	<super-node>false</super-node>
	<label>ioser12.dll</label>
	<weight>12</weight>
	<type>4</type>
</node>
<node>
	<id>21</id>
	<super-node>false</super-node>
	<label>j2pcsc.dll</label>
	<weight>7</weight>
	<type>4</type>
</node>
<node>
	<id>22</id>
	<super-node>false</super-node>
	<label>j2pkcs11.dll</label>
	<weight>41</weight>
	<type>4</type>
</node>
<node>
	<id>23</id>
	<super-node>false</super-node>
	<label>jaas_nt.dll</label>
	<weight>10</weight>
	<type>4</type>
</node>
<node>
	<id>24</id>
	<super-node>false</super-node>
	<label>java-rmi.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>25</id>
	<super-node>false</super-node>
	<label>java.dll</label>
	<weight>126</weight>
	<type>4</type>
</node>
<node>
	<id>26</id>
	<super-node>false</super-node>
	<label>java.exe</label>
	<weight>145</weight>
	<type>4</type>
</node>
<node>
	<id>27</id>
	<super-node>false</super-node>
	<label>javacpl.cpl</label>
	<weight>73</weight>
	<type>-1</type>
</node>
<node>
	<id>28</id>
	<super-node>false</super-node>
	<label>javacpl.exe</label>
	<weight>59</weight>
	<type>4</type>
</node>
<node>
	<id>29</id>
	<super-node>false</super-node>
	<label>javaw.exe</label>
	<weight>145</weight>
	<type>4</type>
</node>
<node>
	<id>30</id>
	<super-node>false</super-node>
	<label>javaws.exe</label>
	<weight>157</weight>
	<type>4</type>
</node>
<node>
	<id>31</id>
	<super-node>false</super-node>
	<label>java_crw_demo.dll</label>
	<weight>14</weight>
	<type>4</type>
</node>
<node>
	<id>32</id>
	<super-node>false</super-node>
	<label>jawt.dll</label>
	<weight>5</weight>
	<type>4</type>
</node>
<node>
	<id>33</id>
	<super-node>false</super-node>
	<label>jbroker.exe</label>
	<weight>79</weight>
	<type>4</type>
</node>
<node>
	<id>34</id>
	<super-node>false</super-node>
	<label>JdbcOdbc.dll</label>
	<weight>36</weight>
	<type>4</type>
</node>
<node>
	<id>35</id>
	<super-node>false</super-node>
	<label>jdwp.dll</label>
	<weight>167</weight>
	<type>4</type>
</node>
<node>
	<id>36</id>
	<super-node>false</super-node>
	<label>jkernel.dll</label>
	<weight>217</weight>
	<type>4</type>
</node>
<node>
	<id>37</id>
	<super-node>false</super-node>
	<label>jli.dll</label>
	<weight>77</weight>
	<type>4</type>
</node>
<node>
	<id>38</id>
	<super-node>false</super-node>
	<label>jp2iexp.dll</label>
	<weight>112</weight>
	<type>4</type>
</node>
<node>
	<id>39</id>
	<super-node>false</super-node>
	<label>jp2launcher.exe</label>
	<weight>23</weight>
	<type>4</type>
</node>
<node>
	<id>40</id>
	<super-node>false</super-node>
	<label>jp2native.dll</label>
	<weight>8</weight>
	<type>4</type>
</node>
<node>
	<id>41</id>
	<super-node>false</super-node>
	<label>jp2ssv.dll</label>
	<weight>41</weight>
	<type>4</type>
</node>
<node>
	<id>42</id>
	<super-node>false</super-node>
	<label>jpeg.dll</label>
	<weight>151</weight>
	<type>4</type>
</node>
<node>
	<id>43</id>
	<super-node>false</super-node>
	<label>jpicom.dll</label>
	<weight>98</weight>
	<type>4</type>
</node>
<node>
	<id>44</id>
	<super-node>false</super-node>
	<label>jpiexp.dll</label>
	<weight>114</weight>
	<type>4</type>
</node>
<node>
	<id>45</id>
	<super-node>false</super-node>
	<label>jpinscp.dll</label>
	<weight>98</weight>
	<type>4</type>
</node>
<node>
	<id>46</id>
	<super-node>false</super-node>
	<label>jpioji.dll</label>
	<weight>65</weight>
	<type>4</type>
</node>
<node>
	<id>47</id>
	<super-node>false</super-node>
	<label>jpishare.dll</label>
	<weight>126</weight>
	<type>4</type>
</node>
<node>
	<id>48</id>
	<super-node>false</super-node>
	<label>jqs.exe</label>
	<weight>153</weight>
	<type>4</type>
</node>
<node>
	<id>49</id>
	<super-node>false</super-node>
	<label>jqsnotify.exe</label>
	<weight>55</weight>
	<type>4</type>
</node>
<node>
	<id>50</id>
	<super-node>false</super-node>
	<label>jsound.dll</label>
	<weight>147</weight>
	<type>4</type>
</node>
<node>
	<id>51</id>
	<super-node>false</super-node>
	<label>jsoundds.dll</label>
	<weight>18</weight>
	<type>4</type>
</node>
<node>
	<id>52</id>
	<super-node>false</super-node>
	<label>keytool.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>53</id>
	<super-node>false</super-node>
	<label>kinit.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>54</id>
	<super-node>false</super-node>
	<label>klist.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>55</id>
	<super-node>false</super-node>
	<label>ktab.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>56</id>
	<super-node>false</super-node>
	<label>management.dll</label>
	<weight>18</weight>
	<type>4</type>
</node>
<node>
	<id>57</id>
	<super-node>false</super-node>
	<label>mlib_image.dll</label>
	<weight>602</weight>
	<type>4</type>
</node>
<node>
	<id>58</id>
	<super-node>false</super-node>
	<label>msvcr71.dll</label>
	<weight>348</weight>
	<type>4</type>
</node>
<node>
	<id>59</id>
	<super-node>false</super-node>
	<label>msvcrt.dll</label>
	<weight>266</weight>
	<type>4</type>
</node>
<node>
	<id>60</id>
	<super-node>false</super-node>
	<label>net.dll</label>
	<weight>77</weight>
	<type>4</type>
</node>
<node>
	<id>61</id>
	<super-node>false</super-node>
	<label>new_plugin</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>62</id>
	<super-node>false</super-node>
	<label>msvcr71.dll</label>
	<weight>348</weight>
	<type>4</type>
</node>
<node>
	<id>63</id>
	<super-node>false</super-node>
	<label>npjp2.dll</label>
	<weight>69</weight>
	<type>4</type>
</node>
<node>
	<id>64</id>
	<super-node>false</super-node>
	<label>nio.dll</label>
	<weight>20</weight>
	<type>4</type>
</node>
<node>
	<id>65</id>
	<super-node>false</super-node>
	<label>npdeployJava1.dll</label>
	<weight>472</weight>
	<type>4</type>
</node>
<node>
	<id>66</id>
	<super-node>false</super-node>
	<label>npjpi160_23.dll</label>
	<weight>141</weight>
	<type>4</type>
</node>
<node>
	<id>67</id>
	<super-node>false</super-node>
	<label>npoji610.dll</label>
	<weight>131</weight>
	<type>4</type>
</node>
<node>
	<id>68</id>
	<super-node>false</super-node>
	<label>npt.dll</label>
	<weight>8</weight>
	<type>4</type>
</node>
<node>
	<id>69</id>
	<super-node>false</super-node>
	<label>orbd.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>70</id>
	<super-node>false</super-node>
	<label>pack200.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>71</id>
	<super-node>false</super-node>
	<label>policytool.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>72</id>
	<super-node>false</super-node>
	<label>regutils.dll</label>
	<weight>278</weight>
	<type>4</type>
</node>
<node>
	<id>73</id>
	<super-node>false</super-node>
	<label>rmi.dll</label>
	<weight>5</weight>
	<type>4</type>
</node>
<node>
	<id>74</id>
	<super-node>false</super-node>
	<label>rmid.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>75</id>
	<super-node>false</super-node>
	<label>rmiregistry.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>76</id>
	<super-node>false</super-node>
	<label>server</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>77</id>
	<super-node>false</super-node>
	<label>jvm.dll</label>
	<weight>4435</weight>
	<type>4</type>
</node>
<node>
	<id>78</id>
	<super-node>false</super-node>
	<label>Xusage.txt</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>79</id>
	<super-node>false</super-node>
	<label>servertool.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>80</id>
	<super-node>false</super-node>
	<label>splashscreen.dll</label>
	<weight>131</weight>
	<type>4</type>
</node>
<node>
	<id>81</id>
	<super-node>false</super-node>
	<label>ssv.dll</label>
	<weight>325</weight>
	<type>4</type>
</node>
<node>
	<id>82</id>
	<super-node>false</super-node>
	<label>ssvagent.exe</label>
	<weight>30</weight>
	<type>4</type>
</node>
<node>
	<id>83</id>
	<super-node>false</super-node>
	<label>sunmscapi.dll</label>
	<weight>16</weight>
	<type>4</type>
</node>
<node>
	<id>84</id>
	<super-node>false</super-node>
	<label>tnameserv.exe</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>85</id>
	<super-node>false</super-node>
	<label>unicows.dll</label>
	<weight>245</weight>
	<type>4</type>
</node>
<node>
	<id>86</id>
	<super-node>false</super-node>
	<label>unpack.dll</label>
	<weight>61</weight>
	<type>4</type>
</node>
<node>
	<id>87</id>
	<super-node>false</super-node>
	<label>unpack200.exe</label>
	<weight>132</weight>
	<type>4</type>
</node>
<node>
	<id>88</id>
	<super-node>false</super-node>
	<label>verify.dll</label>
	<weight>31</weight>
	<type>4</type>
</node>
<node>
	<id>89</id>
	<super-node>false</super-node>
	<label>w2k_lsa_auth.dll</label>
	<weight>10</weight>
	<type>4</type>
</node>
<node>
	<id>90</id>
	<super-node>false</super-node>
	<label>wsdetect.dll</label>
	<weight>108</weight>
	<type>4</type>
</node>
<node>
	<id>91</id>
	<super-node>false</super-node>
	<label>zip.dll</label>
	<weight>46</weight>
	<type>4</type>
</node>
<node>
	<id>92</id>
	<super-node>false</super-node>
	<label>lib</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>93</id>
	<super-node>false</super-node>
	<label>alt-rt.jar</label>
	<weight>64</weight>
	<type>4</type>
</node>
<node>
	<id>94</id>
	<super-node>false</super-node>
	<label>alt-string.jar</label>
	<weight>42</weight>
	<type>4</type>
</node>
<node>
	<id>95</id>
	<super-node>false</super-node>
	<label>applet</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>96</id>
	<super-node>false</super-node>
	<label>audio</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>97</id>
	<super-node>false</super-node>
	<label>soundbank.gm</label>
	<weight>493</weight>
	<type>-1</type>
</node>
<node>
	<id>98</id>
	<super-node>false</super-node>
	<label>calendars.properties</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>99</id>
	<super-node>false</super-node>
	<label>charsets.jar</label>
	<weight>6815</weight>
	<type>4</type>
</node>
<node>
	<id>100</id>
	<super-node>false</super-node>
	<label>classlist</label>
	<weight>82</weight>
	<type>-1</type>
</node>
<node>
	<id>101</id>
	<super-node>false</super-node>
	<label>cmm</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>102</id>
	<super-node>false</super-node>
	<label>CIEXYZ.pf</label>
	<weight>51</weight>
	<type>-1</type>
</node>
<node>
	<id>103</id>
	<super-node>false</super-node>
	<label>GRAY.pf</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>104</id>
	<super-node>false</super-node>
	<label>LINEAR_RGB.pf</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>105</id>
	<super-node>false</super-node>
	<label>PYCC.pf</label>
	<weight>274</weight>
	<type>-1</type>
</node>
<node>
	<id>106</id>
	<super-node>false</super-node>
	<label>sRGB.pf</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>107</id>
	<super-node>false</super-node>
	<label>content-types.properties</label>
	<weight>5</weight>
	<type>-1</type>
</node>
<node>
	<id>108</id>
	<super-node>false</super-node>
	<label>deploy</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>109</id>
	<super-node>false</super-node>
	<label>ffjcext.zip</label>
	<weight>16</weight>
	<type>5</type>
</node>
<node>
	<id>110</id>
	<super-node>false</super-node>
	<label>jqs</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>111</id>
	<super-node>false</super-node>
	<label>ff</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>112</id>
	<super-node>false</super-node>
	<label>chrome</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>113</id>
	<super-node>false</super-node>
	<label>content</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>114</id>
	<super-node>false</super-node>
	<label>overlay.js</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>115</id>
	<super-node>false</super-node>
	<label>overlay.xul</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>116</id>
	<super-node>false</super-node>
	<label>chrome.manifest</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>117</id>
	<super-node>false</super-node>
	<label>install.rdf</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>118</id>
	<super-node>false</super-node>
	<label>ie</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>119</id>
	<super-node>false</super-node>
	<label>jqs_plugin.dll</label>
	<weight>79</weight>
	<type>4</type>
</node>
<node>
	<id>120</id>
	<super-node>false</super-node>
	<label>jqs.conf</label>
	<weight>41</weight>
	<type>-1</type>
</node>
<node>
	<id>121</id>
	<super-node>false</super-node>
	<label>jqsmessages.properties</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>122</id>
	<super-node>false</super-node>
	<label>messages.properties</label>
	<weight>2</weight>
	<type>-1</type>
</node>
<node>
	<id>123</id>
	<super-node>false</super-node>
	<label>messages_de.properties</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>124</id>
	<super-node>false</super-node>
	<label>messages_es.properties</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>125</id>
	<super-node>false</super-node>
	<label>messages_fr.properties</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>126</id>
	<super-node>false</super-node>
	<label>messages_it.properties</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>127</id>
	<super-node>false</super-node>
	<label>messages_ja.properties</label>
	<weight>6</weight>
	<type>-1</type>
</node>
<node>
	<id>128</id>
	<super-node>false</super-node>
	<label>messages_ko.properties</label>
	<weight>5</weight>
	<type>-1</type>
</node>
<node>
	<id>129</id>
	<super-node>false</super-node>
	<label>messages_pt_BR.properties</label>
	<weight>2</weight>
	<type>-1</type>
</node>
<node>
	<id>130</id>
	<super-node>false</super-node>
	<label>messages_sv.properties</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>131</id>
	<super-node>false</super-node>
	<label>messages_zh_CN.properties</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>132</id>
	<super-node>false</super-node>
	<label>messages_zh_HK.properties</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>133</id>
	<super-node>false</super-node>
	<label>messages_zh_TW.properties</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>134</id>
	<super-node>false</super-node>
	<label>splash.gif</label>
	<weight>7</weight>
	<type>2</type>
</node>
<node>
	<id>135</id>
	<super-node>false</super-node>
	<label>deploy.jar</label>
	<weight>3551</weight>
	<type>4</type>
</node>
<node>
	<id>136</id>
	<super-node>false</super-node>
	<label>ext</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>137</id>
	<super-node>false</super-node>
	<label>dnsns.jar</label>
	<weight>8</weight>
	<type>4</type>
</node>
<node>
	<id>138</id>
	<super-node>false</super-node>
	<label>localedata.jar</label>
	<weight>843</weight>
	<type>4</type>
</node>
<node>
	<id>139</id>
	<super-node>false</super-node>
	<label>meta-index</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>140</id>
	<super-node>false</super-node>
	<label>sunjce_provider.jar</label>
	<weight>170</weight>
	<type>4</type>
</node>
<node>
	<id>141</id>
	<super-node>false</super-node>
	<label>sunmscapi.jar</label>
	<weight>33</weight>
	<type>4</type>
</node>
<node>
	<id>142</id>
	<super-node>false</super-node>
	<label>sunpkcs11.jar</label>
	<weight>231</weight>
	<type>4</type>
</node>
<node>
	<id>143</id>
	<super-node>false</super-node>
	<label>flavormap.properties</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>144</id>
	<super-node>false</super-node>
	<label>fontconfig.98.bfc</label>
	<weight>2</weight>
	<type>-1</type>
</node>
<node>
	<id>145</id>
	<super-node>false</super-node>
	<label>fontconfig.98.properties.src</label>
	<weight>7</weight>
	<type>-1</type>
</node>
<node>
	<id>146</id>
	<super-node>false</super-node>
	<label>fontconfig.bfc</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>147</id>
	<super-node>false</super-node>
	<label>fontconfig.properties.src</label>
	<weight>9</weight>
	<type>-1</type>
</node>
<node>
	<id>148</id>
	<super-node>false</super-node>
	<label>fonts</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>149</id>
	<super-node>false</super-node>
	<label>LucidaBrightDemiBold.ttf</label>
	<weight>75</weight>
	<type>-1</type>
</node>
<node>
	<id>150</id>
	<super-node>false</super-node>
	<label>LucidaBrightDemiItalic.ttf</label>
	<weight>75</weight>
	<type>-1</type>
</node>
<node>
	<id>151</id>
	<super-node>false</super-node>
	<label>LucidaBrightItalic.ttf</label>
	<weight>80</weight>
	<type>-1</type>
</node>
<node>
	<id>152</id>
	<super-node>false</super-node>
	<label>LucidaBrightRegular.ttf</label>
	<weight>344</weight>
	<type>-1</type>
</node>
<node>
	<id>153</id>
	<super-node>false</super-node>
	<label>LucidaSansDemiBold.ttf</label>
	<weight>317</weight>
	<type>-1</type>
</node>
<node>
	<id>154</id>
	<super-node>false</super-node>
	<label>LucidaSansRegular.ttf</label>
	<weight>698</weight>
	<type>-1</type>
</node>
<node>
	<id>155</id>
	<super-node>false</super-node>
	<label>LucidaTypewriterBold.ttf</label>
	<weight>234</weight>
	<type>-1</type>
</node>
<node>
	<id>156</id>
	<super-node>false</super-node>
	<label>LucidaTypewriterRegular.ttf</label>
	<weight>242</weight>
	<type>-1</type>
</node>
<node>
	<id>157</id>
	<super-node>false</super-node>
	<label>i386</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>158</id>
	<super-node>false</super-node>
	<label>jvm.cfg</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>159</id>
	<super-node>false</super-node>
	<label>im</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>160</id>
	<super-node>false</super-node>
	<label>indicim.jar</label>
	<weight>10</weight>
	<type>4</type>
</node>
<node>
	<id>161</id>
	<super-node>false</super-node>
	<label>thaiim.jar</label>
	<weight>7</weight>
	<type>4</type>
</node>
<node>
	<id>162</id>
	<super-node>false</super-node>
	<label>images</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>163</id>
	<super-node>false</super-node>
	<label>cursors</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>164</id>
	<super-node>false</super-node>
	<label>cursors.properties</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>165</id>
	<super-node>false</super-node>
	<label>invalid32x32.gif</label>
	<weight>1</weight>
	<type>2</type>
</node>
<node>
	<id>166</id>
	<super-node>false</super-node>
	<label>win32_CopyDrop32x32.gif</label>
	<weight>1</weight>
	<type>2</type>
</node>
<node>
	<id>167</id>
	<super-node>false</super-node>
	<label>win32_CopyNoDrop32x32.gif</label>
	<weight>1</weight>
	<type>2</type>
</node>
<node>
	<id>168</id>
	<super-node>false</super-node>
	<label>win32_LinkDrop32x32.gif</label>
	<weight>1</weight>
	<type>2</type>
</node>
<node>
	<id>169</id>
	<super-node>false</super-node>
	<label>win32_LinkNoDrop32x32.gif</label>
	<weight>1</weight>
	<type>2</type>
</node>
<node>
	<id>170</id>
	<super-node>false</super-node>
	<label>win32_MoveDrop32x32.gif</label>
	<weight>1</weight>
	<type>2</type>
</node>
<node>
	<id>171</id>
	<super-node>false</super-node>
	<label>win32_MoveNoDrop32x32.gif</label>
	<weight>1</weight>
	<type>2</type>
</node>
<node>
	<id>172</id>
	<super-node>false</super-node>
	<label>javaws.jar</label>
	<weight>922</weight>
	<type>4</type>
</node>
<node>
	<id>173</id>
	<super-node>false</super-node>
	<label>jce.jar</label>
	<weight>88</weight>
	<type>4</type>
</node>
<node>
	<id>174</id>
	<super-node>false</super-node>
	<label>jsse.jar</label>
	<weight>631</weight>
	<type>4</type>
</node>
<node>
	<id>175</id>
	<super-node>false</super-node>
	<label>jvm.hprof.txt</label>
	<weight>2</weight>
	<type>0</type>
</node>
<node>
	<id>176</id>
	<super-node>false</super-node>
	<label>launcher.exe</label>
	<weight>46</weight>
	<type>4</type>
</node>
<node>
	<id>177</id>
	<super-node>false</super-node>
	<label>logging.properties</label>
	<weight>2</weight>
	<type>-1</type>
</node>
<node>
	<id>178</id>
	<super-node>false</super-node>
	<label>management</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>179</id>
	<super-node>false</super-node>
	<label>jmxremote.access</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>180</id>
	<super-node>false</super-node>
	<label>jmxremote.password.template</label>
	<weight>2</weight>
	<type>-1</type>
</node>
<node>
	<id>181</id>
	<super-node>false</super-node>
	<label>management.properties</label>
	<weight>14</weight>
	<type>-1</type>
</node>
<node>
	<id>182</id>
	<super-node>false</super-node>
	<label>snmp.acl.template</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>183</id>
	<super-node>false</super-node>
	<label>management-agent.jar</label>
	<weight>1</weight>
	<type>4</type>
</node>
<node>
	<id>184</id>
	<super-node>false</super-node>
	<label>meta-index</label>
	<weight>2</weight>
	<type>-1</type>
</node>
<node>
	<id>185</id>
	<super-node>false</super-node>
	<label>net.properties</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>186</id>
	<super-node>false</super-node>
	<label>plugin.jar</label>
	<weight>1919</weight>
	<type>4</type>
</node>
<node>
	<id>187</id>
	<super-node>false</super-node>
	<label>psfont.properties.ja</label>
	<weight>3</weight>
	<type>-1</type>
</node>
<node>
	<id>188</id>
	<super-node>false</super-node>
	<label>psfontj2d.properties</label>
	<weight>10</weight>
	<type>-1</type>
</node>
<node>
	<id>189</id>
	<super-node>false</super-node>
	<label>resources.jar</label>
	<weight>1133</weight>
	<type>4</type>
</node>
<node>
	<id>190</id>
	<super-node>false</super-node>
	<label>rt.jar</label>
	<weight>49839</weight>
	<type>4</type>
</node>
<node>
	<id>191</id>
	<super-node>false</super-node>
	<label>security</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>192</id>
	<super-node>false</super-node>
	<label>blacklist</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>193</id>
	<super-node>false</super-node>
	<label>cacerts</label>
	<weight>81</weight>
	<type>-1</type>
</node>
<node>
	<id>194</id>
	<super-node>false</super-node>
	<label>java.policy</label>
	<weight>2</weight>
	<type>-1</type>
</node>
<node>
	<id>195</id>
	<super-node>false</super-node>
	<label>java.security</label>
	<weight>9</weight>
	<type>-1</type>
</node>
<node>
	<id>196</id>
	<super-node>false</super-node>
	<label>javaws.policy</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>197</id>
	<super-node>false</super-node>
	<label>local_policy.jar</label>
	<weight>2</weight>
	<type>4</type>
</node>
<node>
	<id>198</id>
	<super-node>false</super-node>
	<label>trusted.libraries</label>
	<weight>14</weight>
	<type>-1</type>
</node>
<node>
	<id>199</id>
	<super-node>false</super-node>
	<label>US_export_policy.jar</label>
	<weight>2</weight>
	<type>4</type>
</node>
<node>
	<id>200</id>
	<super-node>false</super-node>
	<label>servicetag</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>201</id>
	<super-node>false</super-node>
	<label>jdk_header.png</label>
	<weight>8</weight>
	<type>2</type>
</node>
<node>
	<id>202</id>
	<super-node>false</super-node>
	<label>registration.xml</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>203</id>
	<super-node>false</super-node>
	<label>sound.properties</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>204</id>
	<super-node>false</super-node>
	<label>tzmappings</label>
	<weight>7</weight>
	<type>-1</type>
</node>
<node>
	<id>205</id>
	<super-node>false</super-node>
	<label>zi</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>206</id>
	<super-node>false</super-node>
	<label>Africa</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>207</id>
	<super-node>false</super-node>
	<label>Abidjan</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>208</id>
	<super-node>false</super-node>
	<label>Accra</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>209</id>
	<super-node>false</super-node>
	<label>Addis_Ababa</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>210</id>
	<super-node>false</super-node>
	<label>Algiers</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>211</id>
	<super-node>false</super-node>
	<label>Asmara</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>212</id>
	<super-node>false</super-node>
	<label>Bamako</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>213</id>
	<super-node>false</super-node>
	<label>Bangui</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>214</id>
	<super-node>false</super-node>
	<label>Banjul</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>215</id>
	<super-node>false</super-node>
	<label>Bissau</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>216</id>
	<super-node>false</super-node>
	<label>Blantyre</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>217</id>
	<super-node>false</super-node>
	<label>Brazzaville</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>218</id>
	<super-node>false</super-node>
	<label>Bujumbura</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>219</id>
	<super-node>false</super-node>
	<label>Cairo</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>220</id>
	<super-node>false</super-node>
	<label>Casablanca</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>221</id>
	<super-node>false</super-node>
	<label>Ceuta</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>222</id>
	<super-node>false</super-node>
	<label>Conakry</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>223</id>
	<super-node>false</super-node>
	<label>Dakar</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>224</id>
	<super-node>false</super-node>
	<label>Dar_es_Salaam</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>225</id>
	<super-node>false</super-node>
	<label>Djibouti</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>226</id>
	<super-node>false</super-node>
	<label>Douala</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>227</id>
	<super-node>false</super-node>
	<label>El_Aaiun</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>228</id>
	<super-node>false</super-node>
	<label>Freetown</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>229</id>
	<super-node>false</super-node>
	<label>Gaborone</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>230</id>
	<super-node>false</super-node>