<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE graph [
<!ELEMENT graph (data-type, display+, node+, edge+)>
<!ELEMENT data-type (#PCDATA)>
<!ELEMENT display (node-color, edge-color, max-edge-width)>
<!ELEMENT node-color (#PCDATA)>
<!ELEMENT edge-color (#PCDATA)>
<!ELEMENT max-edge-width (#PCDATA)>
<!ELEMENT node (id, super-node, label, weight, type)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT super-node (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT edge (from, to, type, weight)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
]>
<graph>
<data-type>file-system</data-type>
<display>
	<node-color>0,0,255</node-color>
	<edge-color>100,100,100</edge-color>
	<max-edge-width>40</max-edge-width>
</display>
<node>
	<id>0</id>
	<super-node>false</super-node>
	<label>.</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>1</id>
	<super-node>false</super-node>
	<label>2011</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>2</id>
	<super-node>false</super-node>
	<label>ACSC2012</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>3</id>
	<super-node>false</super-node>
	<label>AngularTreemap.docx</label>
	<weight>7376</weight>
	<type>0</type>
</node>
<node>
	<id>4</id>
	<super-node>false</super-node>
	<label>AngularTreemap.pdf</label>
	<weight>2472</weight>
	<type>0</type>
</node>
<node>
	<id>5</id>
	<super-node>false</super-node>
	<label>CRPITTemplate.rtf</label>
	<weight>39</weight>
	<type>0</type>
</node>
<node>
	<id>6</id>
	<super-node>false</super-node>
	<label>infovis2011_v11.doc</label>
	<weight>19131</weight>
	<type>0</type>
</node>
<node>
	<id>7</id>
	<super-node>false</super-node>
	<label>infovis2011_v8_together.doc</label>
	<weight>20981</weight>
	<type>0</type>
</node>
<node>
	<id>8</id>
	<super-node>false</super-node>
	<label>HIC2011</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>9</id>
	<super-node>false</super-node>
	<label>HIC 2011 IOS Press Instructions to authors_Scientific Papers.pdf</label>
	<weight>157</weight>
	<type>0</type>
</node>
<node>
	<id>10</id>
	<super-node>false</super-node>
	<label>HIC 2011 IOS Press MSWord Template with Text.dot</label>
	<weight>34</weight>
	<type>0</type>
</node>
<node>
	<id>11</id>
	<super-node>false</super-node>
	<label>HIC 2011 IOS Press MSWord Template.dot</label>
	<weight>35</weight>
	<type>0</type>
</node>
<node>
	<id>12</id>
	<super-node>false</super-node>
	<label>HIC 2011 Submission Guidelines_Scientific Papers.pdf</label>
	<weight>263</weight>
	<type>0</type>
</node>
<node>
	<id>13</id>
	<super-node>false</super-node>
	<label>HIC 2011 Submission Guidelines_Scientific Papers_0.zip</label>
	<weight>384</weight>
	<type>5</type>
</node>
<node>
	<id>14</id>
	<super-node>false</super-node>
	<label>HIC2011.ppt</label>
	<weight>2358</weight>
	<type>0</type>
</node>
<node>
	<id>15</id>
	<super-node>false</super-node>
	<label>Nguyen_bio.doc</label>
	<weight>22</weight>
	<type>0</type>
</node>
<node>
	<id>16</id>
	<super-node>false</super-node>
	<label>Nguyen_HIC2011.doc</label>
	<weight>551</weight>
	<type>0</type>
</node>
<node>
	<id>17</id>
	<super-node>false</super-node>
	<label>Nguyen_HIC2011_blind.doc</label>
	<weight>549</weight>
	<type>0</type>
</node>
<node>
	<id>18</id>
	<super-node>false</super-node>
	<label>Nguyen_HIC2011_final.doc</label>
	<weight>606</weight>
	<type>0</type>
</node>
<node>
	<id>19</id>
	<super-node>false</super-node>
	<label>Nguyen_HIC2011_final.pdf</label>
	<weight>355</weight>
	<type>0</type>
</node>
<node>
	<id>20</id>
	<super-node>false</super-node>
	<label>Nguyen_HIC2011_v2.doc</label>
	<weight>551</weight>
	<type>0</type>
</node>
<node>
	<id>21</id>
	<super-node>false</super-node>
	<label>Nguyen_ID88_response.doc</label>
	<weight>26</weight>
	<type>0</type>
</node>
<node>
	<id>22</id>
	<super-node>false</super-node>
	<label>Nguyen_photo.jpg</label>
	<weight>744</weight>
	<type>2</type>
</node>
<node>
	<id>23</id>
	<super-node>false</super-node>
	<label>Nguyen_Response.pdf</label>
	<weight>49</weight>
	<type>0</type>
</node>
<node>
	<id>24</id>
	<super-node>false</super-node>
	<label>ICONIP2011</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>25</id>
	<super-node>false</super-node>
	<label>70620113.pdf</label>
	<weight>393</weight>
	<type>0</type>
</node>
<node>
	<id>26</id>
	<super-node>false</super-node>
	<label>ICONIP11-poster.pdf</label>
	<weight>795</weight>
	<type>0</type>
</node>
<node>
	<id>27</id>
	<super-node>false</super-node>
	<label>ICONIP11-poster.ppt</label>
	<weight>1153</weight>
	<type>0</type>
</node>
<node>
	<id>28</id>
	<super-node>false</super-node>
	<label>iconip11_v1.doc</label>
	<weight>1234</weight>
	<type>0</type>
</node>
<node>
	<id>29</id>
	<super-node>false</super-node>
	<label>iconip11_v2.doc</label>
	<weight>1235</weight>
	<type>0</type>
</node>
<node>
	<id>30</id>
	<super-node>false</super-node>
	<label>kdd2011_v7.doc</label>
	<weight>3309</weight>
	<type>0</type>
</node>
<node>
	<id>31</id>
	<super-node>false</super-node>
	<label>latex</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>32</id>
	<super-node>false</super-node>
	<label>0714.zip</label>
	<weight>1492</weight>
	<type>5</type>
</node>
<node>
	<id>33</id>
	<super-node>false</super-node>
	<label>0714_Nguyen.aux</label>
	<weight>2</weight>
	<type>-1</type>
</node>
<node>
	<id>34</id>
	<super-node>false</super-node>
	<label>0714_Nguyen.log</label>
	<weight>9</weight>
	<type>-1</type>
</node>
<node>
	<id>35</id>
	<super-node>false</super-node>
	<label>0714_Nguyen.pdf</label>
	<weight>958</weight>
	<type>0</type>
</node>
<node>
	<id>36</id>
	<super-node>false</super-node>
	<label>0714_Nguyen.synctex.gz</label>
	<weight>58</weight>
	<type>-1</type>
</node>
<node>
	<id>37</id>
	<super-node>false</super-node>
	<label>0714_Nguyen.tex</label>
	<weight>22</weight>
	<type>-1</type>
</node>
<node>
	<id>38</id>
	<super-node>false</super-node>
	<label>0714_SpringerCopyrightForm.pdf</label>
	<weight>50</weight>
	<type>0</type>
</node>
<node>
	<id>39</id>
	<super-node>false</super-node>
	<label>eijkel2.eps</label>
	<weight>13</weight>
	<type>2</type>
</node>
<node>
	<id>40</id>
	<super-node>false</super-node>
	<label>history.txt</label>
	<weight>5</weight>
	<type>0</type>
</node>
<node>
	<id>41</id>
	<super-node>false</super-node>
	<label>iconip11.aux</label>
	<weight>2</weight>
	<type>-1</type>
</node>
<node>
	<id>42</id>
	<super-node>false</super-node>
	<label>iconip11.bbl</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>43</id>
	<super-node>false</super-node>
	<label>iconip11.blg</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>44</id>
	<super-node>false</super-node>
	<label>iconip11.dvi</label>
	<weight>29</weight>
	<type>-1</type>
</node>
<node>
	<id>45</id>
	<super-node>false</super-node>
	<label>iconip11.log</label>
	<weight>10</weight>
	<type>-1</type>
</node>
<node>
	<id>46</id>
	<super-node>false</super-node>
	<label>iconip11.synctex.gz</label>
	<weight>58</weight>
	<type>-1</type>
</node>
<node>
	<id>47</id>
	<super-node>false</super-node>
	<label>images</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>48</id>
	<super-node>false</super-node>
	<label>fig1.jpg</label>
	<weight>130</weight>
	<type>2</type>
</node>
<node>
	<id>49</id>
	<super-node>false</super-node>
	<label>fig2.jpg</label>
	<weight>40</weight>
	<type>2</type>
</node>
<node>
	<id>50</id>
	<super-node>false</super-node>
	<label>fig3.jpg</label>
	<weight>339</weight>
	<type>2</type>
</node>
<node>
	<id>51</id>
	<super-node>false</super-node>
	<label>fig4.jpg</label>
	<weight>305</weight>
	<type>2</type>
</node>
<node>
	<id>52</id>
	<super-node>false</super-node>
	<label>images.zip</label>
	<weight>674</weight>
	<type>5</type>
</node>
<node>
	<id>53</id>
	<super-node>false</super-node>
	<label>llncs.cls</label>
	<weight>42</weight>
	<type>-1</type>
</node>
<node>
	<id>54</id>
	<super-node>false</super-node>
	<label>llncs.dem</label>
	<weight>35</weight>
	<type>-1</type>
</node>
<node>
	<id>55</id>
	<super-node>false</super-node>
	<label>llncs.doc</label>
	<weight>45</weight>
	<type>0</type>
</node>
<node>
	<id>56</id>
	<super-node>false</super-node>
	<label>llncs.dvi</label>
	<weight>71</weight>
	<type>-1</type>
</node>
<node>
	<id>57</id>
	<super-node>false</super-node>
	<label>llncs.ind</label>
	<weight>13</weight>
	<type>-1</type>
</node>
<node>
	<id>58</id>
	<super-node>false</super-node>
	<label>llncsdoc.sty</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>59</id>
	<super-node>false</super-node>
	<label>read.me</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>60</id>
	<super-node>false</super-node>
	<label>splncs.bst</label>
	<weight>21</weight>
	<type>-1</type>
</node>
<node>
	<id>61</id>
	<super-node>false</super-node>
	<label>sprmindx.sty</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>62</id>
	<super-node>false</super-node>
	<label>subjidx.ind</label>
	<weight>2</weight>
	<type>-1</type>
</node>
<node>
	<id>63</id>
	<super-node>false</super-node>
	<label>typeinst.aux</label>
	<weight>2</weight>
	<type>-1</type>
</node>
<node>
	<id>64</id>
	<super-node>false</super-node>
	<label>typeinst.bbl</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>65</id>
	<super-node>false</super-node>
	<label>typeinst.blg</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>66</id>
	<super-node>false</super-node>
	<label>typeinst.dvi</label>
	<weight>26</weight>
	<type>-1</type>
</node>
<node>
	<id>67</id>
	<super-node>false</super-node>
	<label>typeinst.log</label>
	<weight>8</weight>
	<type>-1</type>
</node>
<node>
	<id>68</id>
	<super-node>false</super-node>
	<label>typeinst.tex</label>
	<weight>19</weight>
	<type>-1</type>
</node>
<node>
	<id>69</id>
	<super-node>false</super-node>
	<label>Nguyen_iconip11.pdf</label>
	<weight>843</weight>
	<type>0</type>
</node>
<node>
	<id>70</id>
	<super-node>false</super-node>
	<label>payment-receipt.pdf</label>
	<weight>80</weight>
	<type>0</type>
</node>
<node>
	<id>71</id>
	<super-node>false</super-node>
	<label>payment-receipt_email.pdf</label>
	<weight>94</weight>
	<type>0</type>
</node>
<node>
	<id>72</id>
	<super-node>false</super-node>
	<label>resources</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>73</id>
	<super-node>false</super-node>
	<label>__en.wikipedia.org_wiki_Acute_lymphoblastic_leukemia.pdf</label>
	<weight>500</weight>
	<type>0</type>
</node>
<node>
	<id>74</id>
	<super-node>false</super-node>
	<label>__findarticles.com_p_articles_mi_qa3890_is_200410_ai_n9429273_pg_3__tag=content;col1.pdf</label>
	<weight>132</weight>
	<type>0</type>
</node>
<node>
	<id>75</id>
	<super-node>false</super-node>
	<label>__www.kids-cancer.org_all.pdf</label>
	<weight>138</weight>
	<type>0</type>
</node>
<node>
	<id>76</id>
	<super-node>false</super-node>
	<label>sv-lncs</label>
	<weight>22</weight>
	<type>-1</type>
</node>
<node>
	<id>77</id>
	<super-node>false</super-node>
	<label>sv-lncs.dot</label>
	<weight>22</weight>
	<type>0</type>
</node>
<node>
	<id>78</id>
	<super-node>false</super-node>
	<label>sv_lncs.pdf</label>
	<weight>90</weight>
	<type>0</type>
</node>
<node>
	<id>79</id>
	<super-node>false</super-node>
	<label>typeinst.doc</label>
	<weight>107</weight>
	<type>0</type>
</node>
<node>
	<id>80</id>
	<super-node>false</super-node>
	<label>word.zip</label>
	<weight>147</weight>
	<type>5</type>
</node>
<node>
	<id>81</id>
	<super-node>false</super-node>
	<label>InfoVis2011_x</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>82</id>
	<super-node>false</super-node>
	<label>2011 Calender Phd WorkBook.doc</label>
	<weight>33965</weight>
	<type>0</type>
</node>
<node>
	<id>83</id>
	<super-node>false</super-node>
	<label>infovis2011_v1.doc</label>
	<weight>13908</weight>
	<type>0</type>
</node>
<node>
	<id>84</id>
	<super-node>false</super-node>
	<label>infovis2011_v11.doc</label>
	<weight>27014</weight>
	<type>0</type>
</node>
<node>
	<id>85</id>
	<super-node>false</super-node>
	<label>infovis2011_v2.doc</label>
	<weight>18299</weight>
	<type>0</type>
</node>
<node>
	<id>86</id>
	<super-node>false</super-node>
	<label>infovis2011_v3.doc</label>
	<weight>18297</weight>
	<type>0</type>
</node>
<node>
	<id>87</id>
	<super-node>false</super-node>
	<label>infovis2011_v3_Jie Liang.doc</label>
	<weight>18518</weight>
	<type>0</type>
</node>
<node>
	<id>88</id>
	<super-node>false</super-node>
	<label>infovis2011_v5.doc</label>
	<weight>18520</weight>
	<type>0</type>
</node>
<node>
	<id>89</id>
	<super-node>false</super-node>
	<label>infovis2011_v6.doc</label>
	<weight>20945</weight>
	<type>0</type>
</node>
<node>
	<id>90</id>
	<super-node>false</super-node>
	<label>infovis2011_v6_ss.doc</label>
	<weight>20939</weight>
	<type>0</type>
</node>
<node>
	<id>91</id>
	<super-node>false</super-node>
	<label>infovis2011_v7.doc</label>
	<weight>20151</weight>
	<type>0</type>
</node>
<node>
	<id>92</id>
	<super-node>false</super-node>
	<label>infovis2011_v7_vinh.doc</label>
	<weight>20944</weight>
	<type>0</type>
</node>
<node>
	<id>93</id>
	<super-node>false</super-node>
	<label>infovis2011_v8.doc</label>
	<weight>20151</weight>
	<type>0</type>
</node>
<node>
	<id>94</id>
	<super-node>false</super-node>
	<label>infovis2011_v8_ss.doc</label>
	<weight>20957</weight>
	<type>0</type>
</node>
<node>
	<id>95</id>
	<super-node>false</super-node>
	<label>infovis2011_v8_together.doc</label>
	<weight>20981</weight>
	<type>0</type>
</node>
<node>
	<id>96</id>
	<super-node>false</super-node>
	<label>new3.doc</label>
	<weight>21605</weight>
	<type>0</type>
</node>
<node>
	<id>97</id>
	<super-node>false</super-node>
	<label>Nguyen_infovis2011.pdf</label>
	<weight>11281</weight>
	<type>0</type>
</node>
<node>
	<id>98</id>
	<super-node>false</super-node>
	<label>Word_Win</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>99</id>
	<super-node>false</super-node>
	<label>.DS_Store</label>
	<weight>6</weight>
	<type>-1</type>
</node>
<node>
	<id>100</id>
	<super-node>false</super-node>
	<label>.svn</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>101</id>
	<super-node>false</super-node>
	<label>all-wcprops</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>102</id>
	<super-node>false</super-node>
	<label>entries</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>103</id>
	<super-node>false</super-node>
	<label>format</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>104</id>
	<super-node>false</super-node>
	<label>prop-base</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>105</id>
	<super-node>false</super-node>
	<label>template_journal_word_win_no_teaser.doc.svn-base</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>106</id>
	<super-node>false</super-node>
	<label>template_journal_word_win_no_teaser.dot.svn-base</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>107</id>
	<super-node>false</super-node>
	<label>template_journal_word_win_no_teaser.pdf.svn-base</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>108</id>
	<super-node>false</super-node>
	<label>template_journal_word_win_teaser.doc.svn-base</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>109</id>
	<super-node>false</super-node>
	<label>template_journal_word_win_teaser.dot.svn-base</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>110</id>
	<super-node>false</super-node>
	<label>template_journal_word_win_teaser.pdf.svn-base</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>111</id>
	<super-node>false</super-node>
	<label>props</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>112</id>
	<super-node>false</super-node>
	<label>text-base</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>113</id>
	<super-node>false</super-node>
	<label>template_journal_word_win_no_teaser.doc.svn-base</label>
	<weight>112</weight>
	<type>-1</type>
</node>
<node>
	<id>114</id>
	<super-node>false</super-node>
	<label>template_journal_word_win_no_teaser.dot.svn-base</label>
	<weight>113</weight>
	<type>-1</type>
</node>
<node>
	<id>115</id>
	<super-node>false</super-node>
	<label>template_journal_word_win_no_teaser.pdf.svn-base</label>
	<weight>195</weight>
	<type>-1</type>
</node>
<node>
	<id>116</id>
	<super-node>false</super-node>
	<label>template_journal_word_win_teaser.doc.svn-base</label>
	<weight>544</weight>
	<type>-1</type>
</node>
<node>
	<id>117</id>
	<super-node>false</super-node>
	<label>template_journal_word_win_teaser.dot.svn-base</label>
	<weight>544</weight>
	<type>-1</type>
</node>
<node>
	<id>118</id>
	<super-node>false</super-node>
	<label>template_journal_word_win_teaser.pdf.svn-base</label>
	<weight>218</weight>
	<type>-1</type>
</node>
<node>
	<id>119</id>
	<super-node>false</super-node>
	<label>tmp</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>120</id>
	<super-node>false</super-node>
	<label>prop-base</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>121</id>
	<super-node>false</super-node>
	<label>props</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>122</id>
	<super-node>false</super-node>
	<label>text-base</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>123</id>
	<super-node>false</super-node>
	<label>template_journal_word_win_no_teaser.doc</label>
	<weight>157</weight>
	<type>0</type>
</node>
<node>
	<id>124</id>
	<super-node>false</super-node>
	<label>template_journal_word_win_no_teaser.dot</label>
	<weight>158</weight>
	<type>0</type>
</node>
<node>
	<id>125</id>
	<super-node>false</super-node>
	<label>template_journal_word_win_teaser.doc</label>
	<weight>546</weight>
	<type>0</type>
</node>
<node>
	<id>126</id>
	<super-node>false</super-node>
	<label>template_journal_word_win_teaser.dot</label>
	<weight>548</weight>
	<type>0</type>
</node>
<node>
	<id>127</id>
	<super-node>false</super-node>
	<label>Word_Win.zip</label>
	<weight>2436</weight>
	<type>5</type>
</node>
<node>
	<id>128</id>
	<super-node>false</super-node>
	<label>__MACOSX</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>129</id>
	<super-node>false</super-node>
	<label>Word_Win</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>130</id>
	<super-node>false</super-node>
	<label>._.DS_Store</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>131</id>
	<super-node>false</super-node>
	<label>._template_journal_word_win_no_teaser.doc</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>132</id>
	<super-node>false</super-node>
	<label>._template_journal_word_win_no_teaser.dot</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>133</id>
	<super-node>false</super-node>
	<label>._template_journal_word_win_teaser.doc</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>134</id>
	<super-node>false</super-node>
	<label>._template_journal_word_win_teaser.dot</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>135</id>
	<super-node>false</super-node>
	<label>~WRL4065.tmp</label>
	<weight>20959</weight>
	<type>-1</type>
</node>
<node>
	<id>136</id>
	<super-node>false</super-node>
	<label>IV2011</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>137</id>
	<super-node>false</super-node>
	<label>IV2011_Spam_visualization_finalV.doc</label>
	<weight>3298</weight>
	<type>0</type>
</node>
<node>
	<id>138</id>
	<super-node>false</super-node>
	<label>WordFormat.doc</label>
	<weight>69</weight>
	<type>0</type>
</node>
<node>
	<id>139</id>
	<super-node>false</super-node>
	<label>KDD_x</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>140</id>
	<super-node>false</super-node>
	<label>demo2D</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>141</id>
	<super-node>false</super-node>
	<label>data</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>142</id>
	<super-node>false</super-node>
	<label>250GeneList.csv</label>
	<weight>2</weight>
	<type>0</type>
</node>
<node>
	<id>143</id>
	<super-node>false</super-node>
	<label>AffymetrixAnnotations.csv</label>
	<weight>3391</weight>
	<type>0</type>
</node>
<node>
	<id>144</id>
	<super-node>false</super-node>
	<label>AffymetrixAnnotations_old.csv</label>
	<weight>1442</weight>
	<type>0</type>
</node>
<node>
	<id>145</id>
	<super-node>false</super-node>
	<label>AffymetrixAnnotations_old2.csv</label>
	<weight>1567</weight>
	<type>0</type>
</node>
<node>
	<id>146</id>
	<super-node>false</super-node>
	<label>AffymetrixGeneExpression.csv</label>
	<weight>18854</weight>
	<type>0</type>
</node>
<node>
	<id>147</id>
	<super-node>false</super-node>
	<label>IlluminaSNP.csv</label>
	<weight>10086</weight>
	<type>0</type>
</node>
<node>
	<id>148</id>
	<super-node>false</super-node>
	<label>PatientData.csv</label>
	<weight>25</weight>
	<type>0</type>
</node>
<node>
	<id>149</id>
	<super-node>false</super-node>
	<label>PatientTreatments.csv</label>
	<weight>4</weight>
	<type>0</type>
</node>
<node>
	<id>150</id>
	<super-node>false</super-node>
	<label>processedPatientData.csv</label>
	<weight>35</weight>
	<type>0</type>
</node>
<node>
	<id>151</id>
	<super-node>false</super-node>
	<label>processedPatientData1.csv</label>
	<weight>29</weight>
	<type>0</type>
</node>
<node>
	<id>152</id>
	<super-node>false</super-node>
	<label>processedPatientData2.csv</label>
	<weight>29</weight>
	<type>0</type>
</node>
<node>
	<id>153</id>
	<super-node>false</super-node>
	<label>processedPatientData3.csv</label>
	<weight>33</weight>
	<type>0</type>
</node>
<node>
	<id>154</id>
	<super-node>false</super-node>
	<label>processedPatientData4.csv</label>
	<weight>32</weight>
	<type>0</type>
</node>
<node>
	<id>155</id>
	<super-node>false</super-node>
	<label>processedPatientData5.csv</label>
	<weight>27</weight>
	<type>0</type>
</node>
<node>
	<id>156</id>
	<super-node>false</super-node>
	<label>processedPatientData6.csv</label>
	<weight>33</weight>
	<type>0</type>
</node>
<node>
	<id>157</id>
	<super-node>false</super-node>
	<label>processedPatientData7.csv</label>
	<weight>33</weight>
	<type>0</type>
</node>
<node>
	<id>158</id>
	<super-node>false</super-node>
	<label>README.doc</label>
	<weight>25</weight>
	<type>0</type>
</node>
<node>
	<id>159</id>
	<super-node>false</super-node>
	<label>SimilaritySpace.csv</label>
	<weight>3</weight>
	<type>0</type>
</node>
<node>
	<id>160</id>
	<super-node>false</super-node>
	<label>SNPAnnotations.csv</label>
	<weight>1791</weight>
	<type>0</type>
</node>
<node>
	<id>161</id>
	<super-node>false</super-node>
	<label>SNPAnnotations_old.csv</label>
	<weight>301</weight>
	<type>0</type>
</node>
<node>
	<id>162</id>
	<super-node>false</super-node>
	<label>test.csv</label>
	<weight>32</weight>
	<type>0</type>
</node>
<node>
	<id>163</id>
	<super-node>false</super-node>
	<label>medicalvis.jar</label>
	<weight>7045</weight>
	<type>4</type>
</node>
<node>
	<id>164</id>
	<super-node>false</super-node>
	<label>property_analysis.txt</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>165</id>
	<super-node>false</super-node>
	<label>property_visanalysis.txt</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>166</id>
	<super-node>false</super-node>
	<label>property_visualisation.txt</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>167</id>
	<super-node>false</super-node>
	<label>run.bat</label>
	<weight>1</weight>
	<type>-1</type>
</node>
<node>
	<id>168</id>
	<super-node>false</super-node>
	<label>demo3D</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>169</id>
	<super-node>false</super-node>
	<label>commons-math-2.1-javadoc.jar</label>
	<weight>4902</weight>
	<type>4</type>
</node>
<node>
	<id>170</id>
	<super-node>false</super-node>
	<label>commons-math-2.1-sources.jar</label>
	<weight>1027</weight>
	<type>4</type>
</node>
<node>
	<id>171</id>
	<super-node>false</super-node>
	<label>commons-math-2.1.jar</label>
	<weight>832</weight>
	<type>4</type>
</node>
<node>
	<id>172</id>
	<super-node>false</super-node>
	<label>data</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>173</id>
	<super-node>false</super-node>
	<label>250GeneList.csv</label>
	<weight>2</weight>
	<type>0</type>
</node>
<node>
	<id>174</id>
	<super-node>false</super-node>
	<label>AffymetrixAnnotations.csv</label>
	<weight>3391</weight>
	<type>0</type>
</node>
<node>
	<id>175</id>
	<super-node>false</super-node>
	<label>AffymetrixAnnotations_old.csv</label>
	<weight>1442</weight>
	<type>0</type>
</node>
<node>
	<id>176</id>
	<super-node>false</super-node>
	<label>AffymetrixAnnotations_old2.csv</label>
	<weight>1567</weight>
	<type>0</type>
</node>
<node>
	<id>177</id>
	<super-node>false</super-node>
	<label>AffymetrixGeneExpression.csv</label>
	<weight>18854</weight>
	<type>0</type>
</node>
<node>
	<id>178</id>
	<super-node>false</super-node>
	<label>geneontology.csv</label>
	<weight>17299</weight>
	<type>0</type>
</node>
<node>
	<id>179</id>
	<super-node>false</super-node>
	<label>IlluminaSNP.csv</label>
	<weight>10086</weight>
	<type>0</type>
</node>
<node>
	<id>180</id>
	<super-node>false</super-node>
	<label>PatientData.csv</label>
	<weight>25</weight>
	<type>0</type>
</node>
<node>
	<id>181</id>
	<super-node>false</super-node>
	<label>PatientTreatments.csv</label>
	<weight>4</weight>
	<type>0</type>
</node>
<node>
	<id>182</id>
	<super-node>false</super-node>
	<label>processedPatientData.csv</label>
	<weight>35</weight>
	<type>0</type>
</node>
<node>
	<id>183</id>
	<super-node>false</super-node>
	<label>processedPatientData1.csv</label>
	<weight>29</weight>
	<type>0</type>
</node>
<node>
	<id>184</id>
	<super-node>false</super-node>
	<label>processedPatientData2.csv</label>
	<weight>29</weight>
	<type>0</type>
</node>
<node>
	<id>185</id>
	<super-node>false</super-node>
	<label>processedPatientData3.csv</label>
	<weight>33</weight>
	<type>0</type>
</node>
<node>
	<id>186</id>
	<super-node>false</super-node>
	<label>processedPatientData4.csv</label>
	<weight>32</weight>
	<type>0</type>
</node>
<node>
	<id>187</id>
	<super-node>false</super-node>
	<label>processedPatientData5.csv</label>
	<weight>27</weight>
	<type>0</type>
</node>
<node>
	<id>188</id>
	<super-node>false</super-node>
	<label>processedPatientData6.csv</label>
	<weight>35</weight>
	<type>0</type>
</node>
<node>
	<id>189</id>
	<super-node>false</super-node>
	<label>processedPatientData7.csv</label>
	<weight>35</weight>
	<type>0</type>
</node>
<node>
	<id>190</id>
	<super-node>false</super-node>
	<label>processedPatientData_org.csv</label>
	<weight>35</weight>
	<type>0</type>
</node>
<node>
	<id>191</id>
	<super-node>false</super-node>
	<label>README.doc</label>
	<weight>25</weight>
	<type>0</type>
</node>
<node>
	<id>192</id>
	<super-node>false</super-node>
	<label>SimilaritySpace.csv</label>
	<weight>3</weight>
	<type>0</type>
</node>
<node>
	<id>193</id>
	<super-node>false</super-node>
	<label>SNPAnnotations.csv</label>
	<weight>1791</weight>
	<type>0</type>
</node>
<node>
	<id>194</id>
	<super-node>false</super-node>
	<label>SNPAnnotations_old.csv</label>
	<weight>301</weight>
	<type>0</type>
</node>
<node>
	<id>195</id>
	<super-node>false</super-node>
	<label>test.csv</label>
	<weight>32</weight>
	<type>0</type>
</node>
<node>
	<id>196</id>
	<super-node>false</super-node>
	<label>~$README.doc</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>197</id>
	<super-node>false</super-node>
	<label>j3dcore-d3d.dll</label>
	<weight>823</weight>
	<type>4</type>
</node>
<node>
	<id>198</id>
	<super-node>false</super-node>
	<label>j3dcore-ogl-cg.dll</label>
	<weight>40</weight>
	<type>4</type>
</node>
<node>
	<id>199</id>
	<super-node>false</super-node>
	<label>j3dcore-ogl-chk.dll</label>
	<weight>49</weight>
	<type>4</type>
</node>
<node>
	<id>200</id>
	<super-node>false</super-node>
	<label>j3dcore-ogl.dll</label>
	<weight>163</weight>
	<type>4</type>
</node>
<node>
	<id>201</id>
	<super-node>false</super-node>
	<label>j3dcore.jar</label>
	<weight>2959</weight>
	<type>4</type>
</node>
<node>
	<id>202</id>
	<super-node>false</super-node>
	<label>j3dutils.jar</label>
	<weight>1703</weight>
	<type>4</type>
</node>
<node>
	<id>203</id>
	<super-node>false</super-node>
	<label>j3d_v1</label>
	<weight>0</weight>
	<type>-1</type>
</node>
<node>
	<id>204</id>
	<super-node>false</super-node>
	<label>j3dcore-d3d.dll</label>
	<weight>823</weight>
	<type>4</type>
</node>
<node>
	<id>205</id>
	<super-node>false</super-node>
	<label>j3dcore-ogl-cg.dll</label>
	<weight>40</weight>
	<type>4</type>
</node>
<node>
	<id>206</id>
	<super-node>false</super-node>
	<label>j3dcore-ogl-chk.dll</label>
	<weight>49</weight>
	<type>4</type>
</node>
<node>
	<id>207</id>
	<super-node>false</super-node>
	<label>j3dcore-ogl.dll</label>
	<weight>163</weight>
	<type>4</type>
</node>
<node>
	<id>208</id>
	<super-node>false</super-node>
	<label>j3dcore.jar</label>
	<weight>2959</weight>
	<type>4</type>
</node>
<node>
	<id>209</id>
	<super-node>false</super-node>
	<label>j3dutils.jar</label>
	<weight>1703</weight>
	<type>4</type>
</node>
<node>
	<id>210</id>
	<super-node>false</super-node>
	<label>vecmath.jar</label>
	<weight>325</weight>
	<type>4</type>
</node>
<node>
	<id>211</id>
	<super-node>false</super-node>
	<label>medicalvis_v1.jar</label>
	<weight>9496</weight>
	<type>4</type>
</node>
<node>
	<id>212</id>
	<super-node>false</super-node>
	<label>medicalvis_v2.jar</label>
	<weight>9555</weight>
	<type>4</type>
</node>
<node>
	<id>213</id>
	<super-node>false</super-node>
	<label>property_analysis.txt</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>214</id>
	<super-node>false</super-node>
	<label>property_visanalysis.txt</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>215</id>
	<super-node>false</super-node>
	<label>property_visualisation.txt</label>
	<weight>1</weight>
	<type>0</type>
</node>
<node>
	<id>216</id>
	<super-node>false</super-node>